// Public template-system exports used by generated Electron plugin code.
export * from './system/shared/types';
export * from './system/shared/functions';
export { setupUpdater } from './system/static/electron-api/updater-main';
export { setupShortcuts } from './system/static/electron-api/shortcuts-main';
export type { GlobalShortcutDef, MainAction } from './system/static/electron-api/shortcuts-main';
export { setupDeepLinking, flushDeepLink } from './system/static/electron-api/deep-link-main';
export { setupCSP } from './system/static/electron-api/csp-main';
export { setupMenu, setupContextMenu, setupDockMenu } from './system/static/electron-api/menu-main';
export type { MenuContext, ContextMenuContext, ApplicationMenuFactory, ContextMenuFactory, DockMenuFactory } from './system/static/electron-api/menu-main';
export { setupSplash } from './system/static/electron-api/splash-main';
export { loadWindowState, trackWindowState } from './system/static/electron-api/window-state';
export type { WindowBounds } from './system/static/electron-api/window-state';
export { setupTray } from './system/static/electron-api/tray-main';
export { startLocalServer } from './system/static/electron-api/server-main';
export { appProtocolUrl, isAppProtocolUrl, registerAppProtocolPrivileges, resolveAppProtocolConfig, setupAppProtocol } from './system/static/electron-api/app-protocol-main';
export type { ResolvedAppProtocolConfig } from './system/static/electron-api/app-protocol-main';
export type { TrayMenuContext, TrayMenuFactory } from './system/static/electron-api/tray-main';
export { setManagedWindowAppResolver } from './system/static/electron-api/windows-main';
export type { ManagedWindowAppTarget } from './system/static/electron-api/windows-main';
import './system/static/electron-api/system-main';
import './system/static/electron-api/power-monitor-main';
import './system/static/electron-api/power-save-blocker-main';
import './system/static/electron-api/screen-main';
import './system/static/electron-api/dialogs-main';
import './system/static/electron-api/secure-storage-main';
import './system/static/electron-api/protocol-main';
import './system/static/electron-api/session-main';
import './system/static/electron-api/downloads-main';
import './system/static/electron-api/print-main';
import './system/static/electron-api/desktop-capture-main';
import './system/static/electron-api/auto-launch-main';
import './system/static/electron-api/native-theme-main';
import './system/static/capacitor-api/config-main';
import './system/static/capacitor-api/local-notifications-main';
import './system/static/capacitor-api/action-sheet-main';
import './system/static/capacitor-api/dialog-main';
import './system/static/capacitor-api/app-main';
import './system/static/capacitor-api/browser-main';
import './system/static/capacitor-api/in-app-browser-main';
import './system/static/capacitor-api/filesystem-main';
import './system/static/capacitor-api/preferences-main';
import './system/static/capacitor-api/toast-main';
import './system/static/capacitor-api/clipboard-main';
import './system/static/capacitor-api/device-main';
import './system/static/capacitor-api/network-main';
import './system/static/capacitor-api/file-viewer-main';
import './system/static/capacitor-api/file-transfer-main';
import './system/static/capacitor-api/privacy-screen-main';
import './system/generated/plugins-main-auto';
import './user/plugins-main-user';
