/**
 * CRITICAL PATH — runs in the Electron preload (sandboxed, before the renderer).
 *
 * Exposes `window.CapacitorCustomPlatform` via contextBridge so that third-party
 * Capacitor plugins that declare an `electron` factory in `registerPlugin(...)`:
 *
 *   electron: () => Promise.resolve(window.CapacitorCustomPlatform.plugins.MyPlugin)
 *
 * …can always resolve their implementation regardless of whether `electron-init.js`
 * succeeds in the renderer.  contextBridge runs before any page script and cannot
 * be disrupted by renderer errors.
 *
 * Plugin list sources (merged in order, later entries win):
 *   1. plugins-preload-auto.ts  — generated by `cap-electron sync`
 *   2. plugins-preload-user.ts  — hand-maintained overrides / additions
 *
 * Built-in Capacitor plugins (App, ActionSheet, …) are intentionally NOT listed
 * here — they are defined statically in `electron-init.js` and merged on top of
 * this object in the renderer.  If `electron-init.js` fails, the built-ins fall
 * back to their web implementations; third-party plugins defined here are unaffected.
 *
 * Import from preload.ts:
 *   import './src/system/static/plugins-api/plugins-preload';
 */

import { contextBridge, ipcRenderer, type IpcRendererEvent } from 'electron';

import { pluginsAuto } from '../../generated/plugins-preload-auto';
import { pluginsUser } from '../../../user/plugins-preload-user';

type ListenerFn = (...args: unknown[]) => unknown;
type PluginEntry = { methods: readonly string[]; events?: readonly string[] };

const allPlugins: Record<string, PluginEntry> = { ...pluginsAuto, ...pluginsUser };

// ── Per-plugin event subscription registry ────────────────────────────────────
//
// Layout:  subs[pluginName][eventName] = Map<callbackId, ListenerFn>
// A single ipcRenderer listener is registered per (plugin, eventName) pair and
// fanned out to all JS subscribers.  When the last subscriber for an event is
// removed, the ipcRenderer listener is cleaned up and main is notified.

type SubMap = Map<string, ListenerFn>;

const subs: Record<string, Record<string, SubMap>> = {};
const ipcListeners: Record<string, Record<string, (e: IpcRendererEvent, data: unknown) => void>> = {};

function addSub(plugin: string, eventName: string, fn: ListenerFn): string {
  if (!subs[plugin]) subs[plugin] = {};
  if (!subs[plugin][eventName]) {
    subs[plugin][eventName] = new Map();
    const listener = (_e: IpcRendererEvent, data: unknown) => {
      subs[plugin][eventName]?.forEach((f) => f(data));
    };
    if (!ipcListeners[plugin]) ipcListeners[plugin] = {};
    ipcListeners[plugin][eventName] = listener;
    ipcRenderer.send(`event-add-${plugin}`, eventName);
    ipcRenderer.on(`event-${plugin}-${eventName}`, listener);
  }
  const id = `${plugin}::${eventName}::${Date.now()}-${Math.random().toString(36).slice(2)}`;
  subs[plugin][eventName].set(id, fn);
  return id;
}

function removeSub(callbackId: string): void {
  // id format: "PluginName::eventName::timestamp-random"
  const parts = callbackId.split('::');
  if (parts.length < 2) return;
  const plugin = parts[0];
  const eventName = parts[1];
  const bucket = subs[plugin]?.[eventName];
  if (!bucket) return;
  bucket.delete(callbackId);
  if (bucket.size === 0) {
    const listener = ipcListeners[plugin]?.[eventName];
    if (listener) {
      ipcRenderer.removeListener(`event-${plugin}-${eventName}`, listener);
      delete ipcListeners[plugin][eventName];
    }
    delete subs[plugin][eventName];
    ipcRenderer.send(`event-remove-${plugin}-${eventName}`);
  }
}

function removeAllSubs(plugin: string, eventName?: string): void {
  const pluginSubs = subs[plugin];
  if (!pluginSubs) return;
  const events = eventName ? [eventName] : Object.keys(pluginSubs);
  for (const ev of events) {
    const listener = ipcListeners[plugin]?.[ev];
    if (listener) {
      ipcRenderer.removeListener(`event-${plugin}-${ev}`, listener);
      delete ipcListeners[plugin][ev];
    }
    delete pluginSubs[ev];
    ipcRenderer.send(`event-remove-${plugin}-${ev}`);
  }
}

// ── Build plugin bridges ──────────────────────────────────────────────────────

const bridged: Record<string, Record<string, unknown>> = {};

for (const [name, entry] of Object.entries(allPlugins) as [string, PluginEntry][]) {
  const bridge: Record<string, unknown> = {};

  for (const method of entry.methods) {
    bridge[method] = (opts?: unknown) => ipcRenderer.invoke(`${name}-${method}`, opts);
  }

  if (entry.events?.length) {
    bridge['addListener'] = (eventName: unknown, fn: unknown) =>
      addSub(name, eventName as string, fn as ListenerFn);

    bridge['removeListener'] = (callbackId: unknown) =>
      removeSub(callbackId as string);

    bridge['removeAllListeners'] = (eventName?: unknown) =>
      removeAllSubs(name, eventName as string | undefined);
  }

  bridged[name] = bridge;
}

// ── Expose via contextBridge ──────────────────────────────────────────────────
//
// Sets window.CapacitorCustomPlatform so @capacitor/core recognises this as a
// native Electron platform.  electron-init.js will later extend .plugins with
// the built-in Capacitor plugin bridges — but even if it fails, third-party
// plugins listed here remain accessible.

contextBridge.exposeInMainWorld('CapacitorCustomPlatform', {
  name: 'electron',
  plugins: bridged,
});
